In [1]:
names =  [f"..\\jsons\\rePARSEDOUTPUT-creeper{i}.json" for i in range(1, 11)]
names += [f"..\\jsons\\rePARSEDOUTPUT-pig{i}.json" for i in range(1, 11)]
names += [f"..\\jsons\\rePARSEDOUTPUT-zombie{i}.json" for i in range(1, 10)]
names += [f"..\\jsons\\rePARSEDOUTPUT-sheep{i}.json" for i in range(1, 10)]

In [2]:
import pandas as pd

In [3]:
df_iter = (pd.read_json(src).T for src in names)
df = pd.concat(df_iter).T.drop(["purge", "written"]).T.sample(frac=1)

In [4]:
import cv2
import numpy as np


images = np.asarray(
   [cv2.imread("..\\imgs\\frames_new\\" + i) 
   for i in df.index]
   )
images = np.asarray(images, dtype = "uint8")
labels = np.asarray( 4 * df["Sheep"].astype(bool).astype(int) + 3 * df["Zombie"].astype(bool).astype(int)
                   + 2 * df["Pig"].astype(bool).astype(int) + df["Creeper"].astype(bool).astype(int), dtype="int64")
boundings = list(zip(df["Creeper"], df["Pig"], df["Zombie"], df["Sheep"]))

In [5]:
arr = np.empty((0), dtype = np.float64)
elements = np.empty((len(boundings), 2), dtype = np.int32)
arr_l = np.empty(0, dtype = np.ubyte)

previous = 0

for i, vertex in enumerate(boundings):
    
    elements[i][0] = previous
    
    for label, mobbox in enumerate(vertex):
        
        arr = np.hstack((arr, np.asarray(mobbox).flatten()))
        previous += 4 * len(mobbox)
        
        arr_l = np.hstack((arr_l, np.asarray([label+1]  * len(mobbox), dtype=np.ubyte)))
        
    elements[i][1] = previous
    
for i in range(10):
    
    display(elements[i], arr[ elements[i,0]:elements[i,1]], arr_l[ elements[i,0]>>2:elements[i,1]>>2])



array([0, 4])

array([209.76056338, 178.875     , 129.14084507, 270.3       ])

array([3], dtype=uint8)

array([4, 4])

array([], dtype=float64)

array([], dtype=uint8)

array([4, 8])

array([271.71830986, 165.625     ,   9.70422535,  17.225     ])

array([1], dtype=uint8)

array([ 8, 12])

array([146.30985915, 136.475     ,  10.45070423,  27.825     ])

array([2], dtype=uint8)

array([12, 16])

array([253.05633803, 180.2       ,   7.46478873,  21.2       ])

array([1], dtype=uint8)

array([16, 20])

array([150.04225352, 135.15      ,  29.11267606, 103.35      ])

array([1], dtype=uint8)

array([20, 24])

array([158.25352113, 180.2       ,  47.02816901,  26.5       ])

array([2], dtype=uint8)

array([24, 28])

array([170.1971831 , 162.975     ,  89.57746479, 119.25      ])

array([4], dtype=uint8)

array([28, 32])

array([161.23943662, 143.1       ,  33.5915493 ,  49.025     ])

array([4], dtype=uint8)

array([32, 36])

array([169.45070423, 186.825     ,   5.22535211,  14.575     ])

array([2], dtype=uint8)