In [14]:
names =  [f"..\\jsons\\rePARSEDOUTPUT-creeper{i}.json" for i in range(1, 11)]
names += [f"..\\jsons\\rePARSEDOUTPUT-pig{i}.json" for i in range(1, 11)]
names += [f"..\\jsons\\rePARSEDOUTPUT-zombie{i}.json" for i in range(1, 10)]
names += [f"..\\jsons\\rePARSEDOUTPUT-sheep{i}.json" for i in range(1, 10)]

In [15]:
import pandas as pd

In [16]:
names

['..\\jsons\\rePARSEDOUTPUT-creeper1.json',
 '..\\jsons\\rePARSEDOUTPUT-creeper2.json',
 '..\\jsons\\rePARSEDOUTPUT-creeper3.json',
 '..\\jsons\\rePARSEDOUTPUT-creeper4.json',
 '..\\jsons\\rePARSEDOUTPUT-creeper5.json',
 '..\\jsons\\rePARSEDOUTPUT-creeper6.json',
 '..\\jsons\\rePARSEDOUTPUT-creeper7.json',
 '..\\jsons\\rePARSEDOUTPUT-creeper8.json',
 '..\\jsons\\rePARSEDOUTPUT-creeper9.json',
 '..\\jsons\\rePARSEDOUTPUT-creeper10.json',
 '..\\jsons\\rePARSEDOUTPUT-pig1.json',
 '..\\jsons\\rePARSEDOUTPUT-pig2.json',
 '..\\jsons\\rePARSEDOUTPUT-pig3.json',
 '..\\jsons\\rePARSEDOUTPUT-pig4.json',
 '..\\jsons\\rePARSEDOUTPUT-pig5.json',
 '..\\jsons\\rePARSEDOUTPUT-pig6.json',
 '..\\jsons\\rePARSEDOUTPUT-pig7.json',
 '..\\jsons\\rePARSEDOUTPUT-pig8.json',
 '..\\jsons\\rePARSEDOUTPUT-pig9.json',
 '..\\jsons\\rePARSEDOUTPUT-pig10.json',
 '..\\jsons\\rePARSEDOUTPUT-zombie1.json',
 '..\\jsons\\rePARSEDOUTPUT-zombie2.json',
 '..\\jsons\\rePARSEDOUTPUT-zombie3.json',
 '..\\jsons\\rePARSEDOUTPUT-z

In [17]:
df_iter = (pd.read_json(src).T for src in names)
df = pd.concat(df_iter).T.drop(["purge", "written"]).T.sample(frac=1)

In [18]:
df

Creeper Pig  \
sheep10-00033.png                                                   []  []   
creeper10-00046.png  [[130.6338028169014, 168.275, 13.4366197183098...  []   
creeper8-00069.png   [[254.5492957746479, 217.29999999999998, 44.78...  []   
creeper1-00009.png   [[162.73239436619718, 174.9, 25.38028169014084...  []   
sheep7-00005.png                                                    []  []   
...                                                                ...  ..   
sheep5-00048.png                                                    []  []   
creeper10-00024.png  [[300.0845070422535, 172.25, 32.09859154929577...  []   
zombie4-00041.png                                                   []  []   
creeper8-00023.png                                                  []  []   
sheep6-00032.png                                                    []  []   

                                                                Zombie  \
sheep10-00033.png                                                   []   
creeper10-00046.png                                                 []   
creeper8-00069.png                                                  []   
creeper1-00009.png                                                  []   
sheep7-00005.png                                                    []   
...                                                                ...   
sheep5-00048.png                                                    []   
creeper10-00024.png                                                 []   
zombie4-00041.png    [[191.8450704225352, 125.875, 12.6901408450704...   
creeper8-00023.png                                                  []   
sheep6-00032.png                                                    []   

                                                                 Sheep  
sheep10-00033.png                                                   []  
creeper10-00046.png                                                 []  
creeper8-00069.png                                                  []  
creeper1-00009.png                                                  []  
sheep7-00005.png     [[179.1549295774648, 215.975, 20.1549295774647...  
...                                                                ...  
sheep5-00048.png     [[166.46478873239437, 152.375, 19.408450704225...  
creeper10-00024.png                                                 []  
zombie4-00041.png                                                   []  
creeper8-00023.png                                                  []  
sheep6-00032.png     [[173.1830985915493, 87.45, 16.422535211267604...  

[3028 rows x 4 columns]

In [22]:
import cv2
import numpy as np


images = np.asarray(
   [cv2.imread("..\\imgs\\frames_new\\" + i) 
   for i in df.index]
   )
images = np.asarray(images, dtype = "uint8")
labels = np.asarray( 4 * df["Sheep"].astype(bool).astype(int) + 3 * df["Zombie"].astype(bool).astype(int)
                   + 2 * df["Pig"].astype(bool).astype(int) + df["Creeper"].astype(bool).astype(int), dtype="int64")
boundings = list(zip(df["Creeper"], df["Pig"], df["Zombie"], df["Sheep"]))

In [57]:
arr = np.empty((0), dtype = np.float64)
elements = np.empty((len(boundings), 2), dtype = np.int32)
arr_l = np.empty(0, dtype = np.ubyte)

previous = 0

for i, vertex in enumerate(boundings):
    
    elements[i][0] = previous
    
    for label, mobbox in enumerate(vertex):
        
        arr = np.hstack((arr, np.asarray(mobbox).flatten()))
        previous += 4 * len(mobbox)
        
        arr_l = np.hstack((arr_l, np.asarray([label+1]  * len(mobbox), dtype=np.ubyte)))
        
    elements[i][1] = previous
    
for i in range(10):
    
    display(elements[i], arr[ elements[i,0]:elements[i,1]], arr_l[ elements[i,0]>>2:elements[i,1]>>2])



array([0, 0])

array([], dtype=float64)

array([], dtype=uint8)

array([0, 4])

array([130.63380282, 168.275     ,  13.43661972,  63.6       ])

array([1], dtype=uint8)

array([4, 8])

array([254.54929577, 217.3       ,  44.78873239, 124.55      ])

array([1], dtype=uint8)

array([ 8, 12])

array([162.73239437, 174.9       ,  25.38028169, 116.6       ])

array([1], dtype=uint8)

array([12, 16])

array([179.15492958, 215.975     ,  20.15492958,  37.1       ])

array([4], dtype=uint8)

array([16, 20])

array([156.76056338, 246.45      ,  55.23943662, 100.7       ])

array([2], dtype=uint8)

array([20, 24])

array([85.84507042, 99.375     , 32.09859155, 86.125     ])

array([3], dtype=uint8)

array([24, 28])

array([157.50704225, 157.675     ,   9.70422535,  10.6       ])

array([2], dtype=uint8)

array([28, 32])

array([159.        , 106.        ,  23.88732394,  29.15      ])

array([2], dtype=uint8)

array([32, 36])

array([247.08450704, 141.775     ,  35.83098592,  88.775     ])

array([3], dtype=uint8)